kind: pipeline
name: meta-data

steps:
  - name: dco
    image: algernon/drone-plugin-dco
    depends_on: [ clone ]

---
kind: pipeline
name: build

steps:
  - name: byte-compile
    image: git.madhouse-project.org/drone/buildpack-emacs
    pull: always
    depends_on: [ clone ]
    settings:
      byte_compile:
        - brutalist-theme.el
        - brutalist-dark-theme.el

  - name: checkdoc
    image: git.madhouse-project.org/drone/buildpack-emacs
    pull: always
    depends_on: [ clone ]
    settings:
      checkdoc:
        - brutalist-build.el
        - brutalist-theme.el
        - brutalist-dark-theme.el

  - name: lint
    image: git.madhouse-project.org/drone/buildpack-emacs
    pull: always
    depends_on: [ clone ]
    settings:
      lint:
        - brutalist-build.el
        - brutalist-theme.el
        - brutalist-dark-theme.el
      ignore_warnings:
        - package-prefix
