kind: pipeline
name: meta-data

steps:
  - name: dco
    image: algernon/drone-plugin-dco
    depends_on: [ clone ]

  - name: signature-check
    image: algernon/drone-plugin-signature-check
    depends_on: [ clone ]
    settings:
      keys: [ 10E65DC045EABEFCC5193A26AC1E90BAC433F68F ]
    when:
      event: tag

---
kind: pipeline
name: build

steps:
  - name: bootstrap
    image: registry.madhouse-project.org/algernon/drone-language:emacs
    settings:
      bootstrap: true

  - name: byte-compile
    image: registry.madhouse-project.org/algernon/drone-language:emacs
    depends_on: [ bootstrap ]
    settings:
      byte_compile:
        - brutalist-theme.el
        - brutalist-dark-theme.el

  - name: checkdoc
    image: registry.madhouse-project.org/algernon/drone-language:emacs
    depends_on: [ bootstrap ]
    settings:
      checkdoc:
        - brutalist-build.el
        - brutalist-theme.el
        - brutalist-dark-theme.el

image_pull_secrets:
  - registry_madhouse_project_org
