pipeline:
  dco:
    group: meta
    image: algernon/drone-plugin-dco

  signature-check:
    group: meta
    image: algernon/drone-plugin-signature-check
    when:
      event: tag

  bootstrap:
    image: registry.madhouse-project.org/algernon/drone-language:emacs
    bootstrap: true

  byte-compile:
    group: testing
    image: registry.madhouse-project.org/algernon/drone-language:emacs
    byte_compile:
      - brutalist-theme.el
      - brutalist-dark-theme.el

  checkdoc:
    group: testing
    image: registry.madhouse-project.org/algernon/drone-language:emacs
    checkdoc:
      - brutalist-build.el
      - brutalist-theme.el
      - brutalist-dark-theme.el

image_pull_secrets:
  - registry_madhouse_project_org
